spring:
  application:
    name: mineguard-service-dispatch
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yml
        prefix: ${spring.application.name}

server:
  port: 8085

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.klzw.service.dispatch.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    com.klzw.service.dispatch: debug
