spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_IP:192.168.110.128}:8848
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      group: Service_Dev
      namespace: dev
      discovery:
        namespace: dev
        group: Service_Dev
      config:
        namespace: dev
        group: Service_Dev
  config:
    import:
      - nacos:dispatch-service.yml?refresh=true
      - nacos:common-database.yml?group=Shared_Dev&refresh=true
      - nacos:common-core.yml?group=Shared_Dev&refresh=true
      - nacos:common-redis.yml?group=Shared_Dev&refresh=true
      - nacos:common-web.yml?group=Shared_Dev&refresh=true
      - nacos:common-mq.yml?group=Shared_Dev&refresh=true
mineguard:
  map:
    gaode:
      enabled: true
      api-key: ${GAODE_API_KEY:1df6e350f3e74cba1f7c0b065f62ee2e}
      api-url: "https://restapi.amap.com/v3"
      connect-timeout: 5000
      read-timeout: 10000
      cache-expire: 3600
