package com.klzw.service.dispatch.scheduler;

import com.klzw.service.dispatch.service.DispatchService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class DispatchScheduler {

    private final DispatchService dispatchService;

    /**
     * 每天早上6点自动生成调度任务
     */
    @Scheduled(cron = "0 0 6 * * ?")
    public void autoGenerateDispatchTasks() {
        try {
            log.info("定时执行自动生成调度任务");
            int count = dispatchService.autoGenerateDispatchTasks();
            log.info("定时自动生成调度任务完成，生成数量：{}", count);
        } catch (Exception e) {
            log.error("定时自动生成调度任务异常", e);
        }
    }

    /**
     * 每小时检查一次待执行的调度任务，自动执行
     */
    @Scheduled(cron = "0 0 * * * ?")
    public void checkAndExecuteDispatchTasks() {
        try {
            log.info("定时检查并执行调度任务");
            // 这里可以获取待执行的调度任务并执行
            // 暂时只记录日志
            log.info("定时检查并执行调度任务完成");
        } catch (Exception e) {
            log.error("定时检查并执行调度任务异常", e);
        }
    }
}