package com.klzw.service.dispatch.service;

import com.klzw.service.dispatch.entity.TransportTask;
import com.klzw.service.dispatch.vo.DispatchTaskVO;

import java.time.LocalDateTime;
import java.util.List;

public interface DispatchService {

    TransportTask createDispatchTask(TransportTask task);

    TransportTask updateDispatchTask(TransportTask task);

    boolean deleteDispatchTask(Long taskId);

    boolean executeDispatch(Long taskId);

    boolean cancelDispatchTask(Long taskId);

    TransportTask getDispatchTask(Long taskId);

    List<TransportTask> getDispatchTaskList(Integer status, LocalDateTime startDate, LocalDateTime endDate);

    List<DispatchTaskVO> getAllTaskList(Integer status, LocalDateTime startDate, LocalDateTime endDate);

    List<DispatchTaskVO> getTasksByPlanId(Long planId);

    List<TransportTask> getDispatchTasksByPlanId(Long planId);

    List<TransportTask> getPendingTasksByVehicle(Long vehicleId);

    List<DispatchTaskVO> getPendingTasksByDriver(Long userId);

    void assignVehicle(Long taskId, Long vehicleId);

    void assignDriver(Long taskId, Long driverId);

    Long startTask(Long taskId);

    void updateTaskStatusToInProgress(Long taskId);

    void completeTask(Long taskId);

    void reassignTask(Long taskId, Long newVehicleId, Long newDriverId);

    List<TransportTask> getAvailableTasksForReassignment(LocalDateTime startTime, LocalDateTime endTime);

    int autoGenerateDispatchTasks();

    void dynamicAdjustForVehicleFault(Long vehicleId);

    void dynamicAdjustForDriverLeave(Long driverId);

    void dynamicAdjustForUserLeave(Long userId, String roleCode);

    void dynamicAdjustForRepairmanLeave(Long repairmanId);

    void dynamicAdjustForSafetyOfficerLeave(Long safetyOfficerId);

    void reassignTasksByUserLeave(Long userId, String roleCode);

    void dynamicAdjustForRouteBlock(Long routeId);

    Long createMaintenanceTaskFromFault(java.util.Map<String, Object> faultInfo);

    /**
     * 重新调度已取消的任务
     * 
     * @param taskId 任务ID
     * @return 是否成功
     */
    boolean rescheduleTask(Long taskId);
    
    /**
     * 根据调度任务创建行程
     * 
     * @param task 运输任务
     * @param driverId 司机ID
     * @param vehicleId 车辆ID
     * @return 行程ID
     */
    Long createTripFromTask(TransportTask task, Long driverId, Long vehicleId);
}
