package com.klzw.service.dispatch.service;

import com.klzw.service.dispatch.entity.DispatchTask;
import com.klzw.service.dispatch.entity.DispatchRule;

import java.time.LocalDateTime;
import java.util.List;

public interface DispatchService {

    /**
     * 创建调度任务
     * @param dispatchTask 调度任务
     * @return 调度任务
     */
    DispatchTask createDispatchTask(DispatchTask dispatchTask);

    /**
     * 更新调度任务
     * @param dispatchTask 调度任务
     * @return 调度任务
     */
    DispatchTask updateDispatchTask(DispatchTask dispatchTask);

    /**
     * 执行调度
     * @param taskId 任务ID
     * @return 是否执行成功
     */
    boolean executeDispatch(Long taskId);

    /**
     * 取消调度任务
     * @param taskId 任务ID
     * @return 是否取消成功
     */
    boolean cancelDispatchTask(Long taskId);

    /**
     * 获取调度任务
     * @param taskId 任务ID
     * @return 调度任务
     */
    DispatchTask getDispatchTask(Long taskId);

    /**
     * 获取调度任务列表
     * @param status 状态
     * @param startDate 开始日期
     * @param endDate 结束日期
     * @return 调度任务列表
     */
    List<DispatchTask> getDispatchTaskList(Integer status, LocalDateTime startDate, LocalDateTime endDate);

    /**
     * 自动生成调度任务
     * @return 生成的调度任务数量
     */
    int autoGenerateDispatchTasks();

    /**
     * 获取调度规则
     * @param ruleId 规则ID
     * @return 调度规则
     */
    DispatchRule getDispatchRule(Long ruleId);

    /**
     * 获取调度规则列表
     * @param ruleType 规则类型
     * @param status 状态
     * @return 调度规则列表
     */
    List<DispatchRule> getDispatchRuleList(Integer ruleType, Integer status);
}