package com.klzw.service.dispatch.controller;

import com.klzw.service.dispatch.entity.DispatchTask;
import com.klzw.service.dispatch.entity.DispatchRule;
import com.klzw.service.dispatch.service.DispatchService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;

@Slf4j
@RestController
@RequestMapping("/api/dispatch")
@RequiredArgsConstructor
public class DispatchController {

    private final DispatchService dispatchService;

    /**
     * 创建调度任务
     * @param dispatchTask 调度任务
     * @return 调度任务
     */
    @PostMapping("/task")
    public DispatchTask createDispatchTask(@RequestBody DispatchTask dispatchTask) {
        try {
            log.debug("创建调度任务：{}", dispatchTask);
            return dispatchService.createDispatchTask(dispatchTask);
        } catch (Exception e) {
            log.error("创建调度任务异常", e);
            throw e;
        }
    }

    /**
     * 更新调度任务
     * @param dispatchTask 调度任务
     * @return 调度任务
     */
    @PutMapping("/task")
    public DispatchTask updateDispatchTask(@RequestBody DispatchTask dispatchTask) {
        try {
            log.debug("更新调度任务：{}", dispatchTask);
            return dispatchService.updateDispatchTask(dispatchTask);
        } catch (Exception e) {
            log.error("更新调度任务异常", e);
            throw e;
        }
    }

    /**
     * 执行调度
     * @param taskId 任务ID
     * @return 是否执行成功
     */
    @PostMapping("/task/{taskId}/execute")
    public boolean executeDispatch(@PathVariable Long taskId) {
        try {
            log.debug("执行调度任务：ID={}", taskId);
            return dispatchService.executeDispatch(taskId);
        } catch (Exception e) {
            log.error("执行调度任务异常", e);
            throw e;
        }
    }

    /**
     * 取消调度任务
     * @param taskId 任务ID
     * @return 是否取消成功
     */
    @PostMapping("/task/{taskId}/cancel")
    public boolean cancelDispatchTask(@PathVariable Long taskId) {
        try {
            log.debug("取消调度任务：ID={}", taskId);
            return dispatchService.cancelDispatchTask(taskId);
        } catch (Exception e) {
            log.error("取消调度任务异常", e);
            throw e;
        }
    }

    /**
     * 获取调度任务
     * @param taskId 任务ID
     * @return 调度任务
     */
    @GetMapping("/task/{taskId}")
    public DispatchTask getDispatchTask(@PathVariable Long taskId) {
        try {
            log.debug("获取调度任务：ID={}", taskId);
            return dispatchService.getDispatchTask(taskId);
        } catch (Exception e) {
            log.error("获取调度任务异常", e);
            throw e;
        }
    }

    /**
     * 获取调度任务列表
     * @param status 状态
     * @param startDate 开始日期
     * @param endDate 结束日期
     * @return 调度任务列表
     */
    @GetMapping("/task/list")
    public List<DispatchTask> getDispatchTaskList(
            @RequestParam(value = "status", required = false) Integer status,
            @RequestParam("startDate") String startDate,
            @RequestParam("endDate") String endDate) {
        try {
            LocalDateTime start = LocalDateTime.parse(startDate);
            LocalDateTime end = LocalDateTime.parse(endDate);
            log.debug("获取调度任务列表：状态={}, 开始日期={}, 结束日期={}", 
                    status, startDate, endDate);
            return dispatchService.getDispatchTaskList(status, start, end);
        } catch (Exception e) {
            log.error("获取调度任务列表异常", e);
            throw e;
        }
    }

    /**
     * 自动生成调度任务
     * @return 生成的调度任务数量
     */
    @PostMapping("/task/auto-generate")
    public int autoGenerateDispatchTasks() {
        try {
            log.debug("自动生成调度任务");
            return dispatchService.autoGenerateDispatchTasks();
        } catch (Exception e) {
            log.error("自动生成调度任务异常", e);
            throw e;
        }
    }

    /**
     * 获取调度规则
     * @param ruleId 规则ID
     * @return 调度规则
     */
    @GetMapping("/rule/{ruleId}")
    public DispatchRule getDispatchRule(@PathVariable Long ruleId) {
        try {
            log.debug("获取调度规则：ID={}", ruleId);
            return dispatchService.getDispatchRule(ruleId);
        } catch (Exception e) {
            log.error("获取调度规则异常", e);
            throw e;
        }
    }

    /**
     * 获取调度规则列表
     * @param ruleType 规则类型
     * @param status 状态
     * @return 调度规则列表
     */
    @GetMapping("/rule/list")
    public List<DispatchRule> getDispatchRuleList(
            @RequestParam(value = "ruleType", required = false) Integer ruleType,
            @RequestParam(value = "status", required = false) Integer status) {
        try {
            log.debug("获取调度规则列表：规则类型={}, 状态={}", ruleType, status);
            return dispatchService.getDispatchRuleList(ruleType, status);
        } catch (Exception e) {
            log.error("获取调度规则列表异常", e);
            throw e;
        }
    }
}