server:
  port: 8081
spring:
  application:
    name: user-service-prod
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_IP:192.168.110.128}:8848
      username: ${NACOS_USERNAME_PROD:nacos}
      password: ${NACOS_PASSWORD_PROD:nacos}
      discovery:
        namespace: prod
        group: Service_Prod
      config:
        namespace: prod
        group: Service_Prod
  config:
    import:
      - nacos:user-service.yml?group=Service_Prod&refresh=true
      - nacos:common-core.yml?group=Shared_Prod&refresh=true
      - nacos:common-auth.yml?group=Shared_Prod&refresh=true
      - nacos:common-redis.yml?group=Shared_Prod&refresh=true
      - nacos:common-datasource.yml?group=Shared_Prod&refresh=true
      - nacos:common-file.yml?group=Shared_Prod&refresh=true
      - nacos:common-web.yml?group=Shared_Prod&refresh=true
